In [2]:
from ib_insync import *
from IPython.display import display, clear_output
import pandas as pd
import numpy as np
import datetime as dt
util.startLoop()

ib = IB()
ib.connect()   

contract = Forex('EURUSD')

def onBarUpdate(bars, hasnewBar):
    global df 
    df = pd.DataFrame(bars)[['date', 'open', 'high', 'low', 'close', 'volume']].iloc[:-1] # only take the date and closing price, execute the last row
    df.set_index('date', inplace = True) 
    clear_output(wait=True)
    display(df)

bars = ib.reqHistoricalData(
    contract,
    endDateTime='', # current data
    durationStr='10 Y',
    barSizeSetting='1 day',
    whatToShow='MIDPOINT',
    useRTH=True,
    formatDate=2,
    keepUpToDate=True,
    timeout = 0
)

In [3]:
bars.updateEvent += onBarUpdate

                open      high       low     close  volume
date
2014-08-11  1.340725  1.341200  1.338035  1.338495    -1.0
2014-08-12  1.338480  1.338625  1.333610  1.336935    -1.0
2014-08-13  1.336790  1.341575  1.334235  1.336445    -1.0
2014-08-14  1.336470  1.340785  1.334855  1.336500    -1.0
2014-08-15  1.336720  1.341190  1.335890  1.340100    -1.0
...              ...       ...       ...       ...     ...
2024-07-31  1.081475  1.084935  1.080195  1.082575    -1.0
2024-08-01  1.082450  1.083550  1.077750  1.079155    -1.0
2024-08-02  1.079175  1.092670  1.078195  1.090910    -1.0
2024-08-05  1.092150  1.100900  1.089240  1.095250    -1.0
2024-08-06  1.095045  1.096315  1.090375  1.093145    -1.0

[2591 rows x 5 columns]

In [ ]:
ib.cancelHistoricalData(bars)

Error 162, reqId 83: Historical Market Data Service error message:API historical data query cancelled: 83

In [6]:
df.to_csv("daily_eurusd.csv")